-- Local development schema for dow_manage.
-- This intentionally contains no production employee or attendance data.

create table if not exists public.employees (
    name text primary key,
    org text,
    join_date date,
    leave_date date,
    created_at timestamptz not null default now(),
    email text,
    rank text,
    is_leader boolean not null default false,
    shift text,
    pin text not null,
    is_admin boolean not null default false
);

create table if not exists public.attendance_records (
    manager_key text primary key,
    name text not null,
    date date not null,
    shift text,
    in_time text,
    out_time text,
    status_in boolean not null default false,
    status_out boolean not null default false,
    status_leave boolean not null default false,
    manager_reason text not null default '',
    employee_explanation text not null default '',
    early_punch_mode text not null default '',
    is_anomalous boolean not null default false,
    updated_at timestamptz not null default now(),
    reason text not null default ''
);

create index if not exists attendance_records_name_date_idx
    on public.attendance_records (name, date);

create table if not exists public.attendance_anomalies (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    date date not null,
    name text not null,
    reason text,
    explanation text,
    status text not null default 'requested',
    manager_key text not null unique
);

create index if not exists attendance_anomalies_name_date_idx
    on public.attendance_anomalies (name, date);

create table if not exists public.attendance_supplements (
    id bigint generated by default as identity primary key,
    name text not null,
    date date not null,
    type text not null,
    details text,
    status text not null default 'pending',
    created_at timestamptz not null default now(),
    unique (name, date)
);

create table if not exists public.attendance_holidays (
    date date primary key,
    name text not null
);

create table if not exists public.attendance_reports (
    report_key text primary key,
    period_start date not null,
    period_end date not null,
    report_date date,
    saved_at timestamptz not null default now(),
    names jsonb not null default '[]'::jsonb,
    snapshot jsonb not null default '{}'::jsonb,
    is_printed boolean not null default false,
    printed_at timestamptz
);

create table if not exists public.approvals (
    id bigint generated by default as identity primary key,
    type text not null,
    applicant text not null,
    data jsonb not null default '{}'::jsonb,
    amount numeric not null default 0,
    status text not null default 'pending',
    note text not null default '',
    decided_by text,
    decided_at timestamptz,
    current_step integer not null default 1,
    approval_steps jsonb not null default '[]'::jsonb,
    attachments jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists approvals_applicant_created_at_idx
    on public.approvals (applicant, created_at desc);

create table if not exists public.app_settings (
    module text not null,
    key text not null,
    value jsonb,
    updated_at timestamptz not null default now(),
    primary key (module, key)
);

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema public to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

alter default privileges in schema public
    grant select, insert, update, delete on tables to anon, authenticated, service_role;
alter default privileges in schema public
    grant usage, select on sequences to anon, authenticated, service_role;

insert into storage.buckets (id, name, public, file_size_limit)
values ('approval-files', 'approval-files', false, 10485760)
on conflict (id) do update
set file_size_limit = excluded.file_size_limit;

create policy "local approval files select"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'approval-files');

create policy "local approval files insert"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'approval-files');

create policy "local approval files update"
on storage.objects for update
to anon, authenticated
using (bucket_id = 'approval-files')
with check (bucket_id = 'approval-files');

create policy "local approval files delete"
on storage.objects for delete
to anon, authenticated
using (bucket_id = 'approval-files');
